#!/bin/sh
local branches branch
    branches=$(git branch -vv) &&
      branch=$(echo "$branches" |sed "s/* //" | awk '{print $1}' |fzf --preview 'git trace --color=always {} ') &&
        git checkout $(echo "$branch" | awk '{print $1}' | sed "s/.* //")

